#[test_only]
module suiqr::payments_tests;

use std::option;
use std::string;
use sui::clock::{Self, Clock};
use sui::coin::{Self, Coin};
use sui::sui::SUI;
use sui::test_scenario as ts;
use suiqr::payments::{Self, MerchantRegistry, AdminCap};

const ADMIN: address = @0xA1;
const MERCHANT: address = @0xA2; // matches test-vector claimer
const OTHER_MERCHANT: address = @0xA3;
const PAYER: address = @0xB1;

// ─── Test vectors ──────────────────────────────────────────────────────
// Generated by scripts/gen-test-vectors.ts — regenerate if ClaimMessage shape changes.
// issuer pubkey  hex: 2152f8d19b791d24453242e15f2eab6cb7cffa7b6a5ed30097960e069881db12
// signature       hex: a4cf179bdc65d0cc24c4dde418eeaeb53325a94677541b54638591d164d9c34c6bf9a8bbc290d1728723545b1dd9c6d7b3eb7746874d6f4388c8379fe1a31603

const ISSUER_PUBKEY: vector<u8> = vector[33u8, 82u8, 248u8, 209u8, 155u8, 121u8, 29u8, 36u8, 69u8, 50u8, 66u8, 225u8, 95u8, 46u8, 171u8, 108u8, 183u8, 207u8, 250u8, 123u8, 106u8, 94u8, 211u8, 0u8, 151u8, 150u8, 14u8, 6u8, 152u8, 129u8, 219u8, 18u8];
const TEST_SIGNATURE: vector<u8> = vector[164u8, 207u8, 23u8, 155u8, 220u8, 101u8, 208u8, 204u8, 36u8, 196u8, 221u8, 228u8, 24u8, 238u8, 174u8, 181u8, 51u8, 37u8, 169u8, 70u8, 119u8, 84u8, 27u8, 84u8, 99u8, 133u8, 145u8, 209u8, 100u8, 217u8, 195u8, 76u8, 107u8, 249u8, 168u8, 187u8, 194u8, 144u8, 209u8, 114u8, 135u8, 35u8, 84u8, 91u8, 29u8, 217u8, 198u8, 215u8, 179u8, 235u8, 119u8, 70u8, 135u8, 77u8, 111u8, 67u8, 136u8, 200u8, 55u8, 159u8, 225u8, 163u8, 22u8, 3u8];
const TEST_UEN: vector<u8> = vector[50u8, 48u8, 50u8, 48u8, 49u8, 50u8, 51u8, 52u8, 53u8, 90u8];
const TEST_NONCE: vector<u8> = vector[171u8, 171u8, 171u8, 171u8, 171u8, 171u8, 171u8, 171u8, 171u8, 171u8, 171u8, 171u8, 171u8, 171u8, 171u8, 171u8, 171u8, 171u8, 171u8, 171u8, 171u8, 171u8, 171u8, 171u8, 171u8, 171u8, 171u8, 171u8, 171u8, 171u8, 171u8, 171u8];
const TEST_EXPIRES_AT_MS: u64 = 9999999999999;
const TEST_CHAIN_ID: u8 = 0;

// ─── Helpers ───────────────────────────────────────────────────────────

fun new_clock_at(t_ms: u64, ctx: &mut TxContext): Clock {
    let mut c = clock::create_for_testing(ctx);
    clock::set_for_testing(&mut c, t_ms);
    c
}

fun setup_registry(scenario: &mut ts::Scenario) {
    ts::next_tx(scenario, ADMIN);
    payments::init_for_testing(ts::ctx(scenario));
}

fun init_issuer(scenario: &mut ts::Scenario, pubkey: vector<u8>, chain_id: u8) {
    ts::next_tx(scenario, ADMIN);
    let mut registry = ts::take_shared<MerchantRegistry>(scenario);
    payments::set_initial_issuer_pubkey(&mut registry, pubkey, chain_id, ts::ctx(scenario));
    ts::return_shared(registry);
}

// ─── Test: happy-path register with real ed25519 vector ────────────────

#[test]
fun register_merchant_happy_path_real_signature() {
    let mut scenario = ts::begin(ADMIN);
    setup_registry(&mut scenario);
    init_issuer(&mut scenario, ISSUER_PUBKEY, TEST_CHAIN_ID);

    ts::next_tx(&mut scenario, MERCHANT);
    let mut registry = ts::take_shared<MerchantRegistry>(&mut scenario);
    let clock = new_clock_at(1000, ts::ctx(&mut scenario));

    payments::register_merchant(
        &mut registry,
        TEST_UEN,
        TEST_NONCE,
        TEST_SIGNATURE,
        TEST_EXPIRES_AT_MS,
        option::some(string::utf8(b"ipfs://merchant-meta")),
        &clock,
        ts::ctx(&mut scenario),
    );

    assert!(payments::is_registered(&registry, TEST_UEN), 0);
    assert!(payments::merchant_address(&registry, TEST_UEN) == MERCHANT, 1);

    clock::destroy_for_testing(clock);
    ts::return_shared(registry);
    ts::end(scenario);
}

// ─── Test: init-race guard ─────────────────────────────────────────────

#[test]
#[expected_failure(abort_code = 8, location = suiqr::payments)] // E_REGISTRY_NOT_INITIALIZED
fun register_before_issuer_set_fails() {
    let mut scenario = ts::begin(ADMIN);
    setup_registry(&mut scenario);

    ts::next_tx(&mut scenario, MERCHANT);
    let mut registry = ts::take_shared<MerchantRegistry>(&mut scenario);
    let clock = new_clock_at(1000, ts::ctx(&mut scenario));

    payments::register_merchant(
        &mut registry,
        TEST_UEN,
        TEST_NONCE,
        TEST_SIGNATURE,
        TEST_EXPIRES_AT_MS,
        option::none(),
        &clock,
        ts::ctx(&mut scenario),
    );

    clock::destroy_for_testing(clock);
    ts::return_shared(registry);
    ts::end(scenario);
}

// ─── Test: expired attestation ─────────────────────────────────────────

#[test]
#[expected_failure(abort_code = 9, location = suiqr::payments)] // E_ATTESTATION_EXPIRED
fun register_expired_attestation_fails() {
    let mut scenario = ts::begin(ADMIN);
    setup_registry(&mut scenario);
    init_issuer(&mut scenario, ISSUER_PUBKEY, TEST_CHAIN_ID);

    ts::next_tx(&mut scenario, MERCHANT);
    let mut registry = ts::take_shared<MerchantRegistry>(&mut scenario);
    let expires_at_ms = 1000u64;
    let clock = new_clock_at(2000, ts::ctx(&mut scenario)); // past expiry

    payments::register_merchant(
        &mut registry,
        TEST_UEN,
        TEST_NONCE,
        TEST_SIGNATURE,
        expires_at_ms,
        option::none(),
        &clock,
        ts::ctx(&mut scenario),
    );

    clock::destroy_for_testing(clock);
    ts::return_shared(registry);
    ts::end(scenario);
}

// ─── Test: bad signature ───────────────────────────────────────────────

#[test]
#[expected_failure(abort_code = 5, location = suiqr::payments)] // E_INVALID_ATTESTATION
fun register_bad_signature_fails() {
    let mut scenario = ts::begin(ADMIN);
    setup_registry(&mut scenario);
    init_issuer(&mut scenario, ISSUER_PUBKEY, TEST_CHAIN_ID);

    ts::next_tx(&mut scenario, MERCHANT);
    let mut registry = ts::take_shared<MerchantRegistry>(&mut scenario);
    let clock = new_clock_at(1000, ts::ctx(&mut scenario));

    // Use a zeroed signature — guaranteed invalid
    let bad_sig = vector[0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8];

    payments::register_merchant(
        &mut registry,
        TEST_UEN,
        TEST_NONCE,
        bad_sig,
        TEST_EXPIRES_AT_MS,
        option::none(),
        &clock,
        ts::ctx(&mut scenario),
    );

    clock::destroy_for_testing(clock);
    ts::return_shared(registry);
    ts::end(scenario);
}

// ─── Test: wrong chain_id rejects the signature ────────────────────────

#[test]
#[expected_failure(abort_code = 5, location = suiqr::payments)] // E_INVALID_ATTESTATION (BCS msg differs)
fun register_wrong_chain_id_fails() {
    let mut scenario = ts::begin(ADMIN);
    setup_registry(&mut scenario);
    // Init with chain_id=1; vector was signed for chain_id=0
    init_issuer(&mut scenario, ISSUER_PUBKEY, 1);

    ts::next_tx(&mut scenario, MERCHANT);
    let mut registry = ts::take_shared<MerchantRegistry>(&mut scenario);
    let clock = new_clock_at(1000, ts::ctx(&mut scenario));

    payments::register_merchant(
        &mut registry,
        TEST_UEN,
        TEST_NONCE,
        TEST_SIGNATURE,
        TEST_EXPIRES_AT_MS,
        option::none(),
        &clock,
        ts::ctx(&mut scenario),
    );

    clock::destroy_for_testing(clock);
    ts::return_shared(registry);
    ts::end(scenario);
}

// ─── Test: double-claim same UEN fails ─────────────────────────────────

#[test]
#[expected_failure(abort_code = 1, location = suiqr::payments)] // E_UEN_ALREADY_CLAIMED
fun double_claim_uen_fails() {
    let mut scenario = ts::begin(ADMIN);
    setup_registry(&mut scenario);
    init_issuer(&mut scenario, ISSUER_PUBKEY, TEST_CHAIN_ID);

    // First claim — real vector, succeeds
    ts::next_tx(&mut scenario, MERCHANT);
    {
        let mut registry = ts::take_shared<MerchantRegistry>(&mut scenario);
        let clock = new_clock_at(1000, ts::ctx(&mut scenario));
        payments::register_merchant(
            &mut registry,
            TEST_UEN,
            TEST_NONCE,
            TEST_SIGNATURE,
            TEST_EXPIRES_AT_MS,
            option::none(),
            &clock,
            ts::ctx(&mut scenario),
        );
        clock::destroy_for_testing(clock);
        ts::return_shared(registry);
    };

    // Second claim of same UEN — should abort with E_UEN_ALREADY_CLAIMED
    // Use a different nonce so we hit the UEN_ALREADY check, not nonce-replay.
    ts::next_tx(&mut scenario, MERCHANT);
    let mut registry = ts::take_shared<MerchantRegistry>(&mut scenario);
    let clock = new_clock_at(2000, ts::ctx(&mut scenario));
    let other_nonce = vector[1u8, 2u8, 3u8, 4u8, 5u8, 6u8, 7u8, 8u8, 9u8, 10u8, 11u8, 12u8, 13u8, 14u8, 15u8, 16u8, 17u8, 18u8, 19u8, 20u8, 21u8, 22u8, 23u8, 24u8, 25u8, 26u8, 27u8, 28u8, 29u8, 30u8, 31u8, 32u8];

    payments::register_merchant(
        &mut registry,
        TEST_UEN,
        other_nonce,
        TEST_SIGNATURE, // sig won't verify but UEN check fires first
        TEST_EXPIRES_AT_MS,
        option::none(),
        &clock,
        ts::ctx(&mut scenario),
    );

    clock::destroy_for_testing(clock);
    ts::return_shared(registry);
    ts::end(scenario);
}

// ─── Test: pay happy path ──────────────────────────────────────────────

#[test]
fun pay_succeeds_and_emits_receipt() {
    let mut scenario = ts::begin(ADMIN);
    setup_registry(&mut scenario);

    // Use test bypass to register (we exercise register path in other tests)
    ts::next_tx(&mut scenario, ADMIN);
    {
        let mut registry = ts::take_shared<MerchantRegistry>(&mut scenario);
        let clock = new_clock_at(1000, ts::ctx(&mut scenario));
        payments::register_for_testing(
            &mut registry,
            TEST_UEN,
            MERCHANT,
            &clock,
            ts::ctx(&mut scenario),
        );
        clock::destroy_for_testing(clock);
        ts::return_shared(registry);
    };

    // Payer pays 1_000_000 mist (= 0.001 SUI) — small ticket
    ts::next_tx(&mut scenario, PAYER);
    let registry = ts::take_shared<MerchantRegistry>(&mut scenario);
    let clock = new_clock_at(2000, ts::ctx(&mut scenario));
    let coin: Coin<SUI> = coin::mint_for_testing<SUI>(1_000_000, ts::ctx(&mut scenario));

    payments::pay<SUI>(
        &registry,
        TEST_UEN,
        coin,
        option::some(b"chicken rice"),
        150, // SGD $1.50 minor units
        option::some(b"quote-meta-bcs-bytes"),
        &clock,
        ts::ctx(&mut scenario),
    );

    clock::destroy_for_testing(clock);
    ts::return_shared(registry);

    // Verify merchant received the coin
    ts::next_tx(&mut scenario, MERCHANT);
    let received = ts::take_from_sender<Coin<SUI>>(&mut scenario);
    assert!(coin::value(&received) == 1_000_000, 0);
    ts::return_to_sender(&mut scenario, received);

    ts::end(scenario);
}

// ─── Test: pay to unregistered UEN fails ───────────────────────────────

#[test]
#[expected_failure(abort_code = 2, location = suiqr::payments)] // E_UEN_NOT_REGISTERED
fun pay_unregistered_uen_fails() {
    let mut scenario = ts::begin(ADMIN);
    setup_registry(&mut scenario);

    ts::next_tx(&mut scenario, PAYER);
    let registry = ts::take_shared<MerchantRegistry>(&mut scenario);
    let clock = new_clock_at(1000, ts::ctx(&mut scenario));
    let coin: Coin<SUI> = coin::mint_for_testing<SUI>(1_000_000, ts::ctx(&mut scenario));

    payments::pay<SUI>(
        &registry,
        TEST_UEN, // never registered
        coin,
        option::none(),
        0,
        option::none(),
        &clock,
        ts::ctx(&mut scenario),
    );

    clock::destroy_for_testing(clock);
    ts::return_shared(registry);
    ts::end(scenario);
}

// ─── Test: pay zero amount fails ───────────────────────────────────────

#[test]
#[expected_failure(abort_code = 4, location = suiqr::payments)] // E_PAYMENT_BELOW_MIN
fun pay_zero_amount_fails() {
    let mut scenario = ts::begin(ADMIN);
    setup_registry(&mut scenario);

    ts::next_tx(&mut scenario, ADMIN);
    {
        let mut registry = ts::take_shared<MerchantRegistry>(&mut scenario);
        let clock = new_clock_at(1000, ts::ctx(&mut scenario));
        payments::register_for_testing(&mut registry, TEST_UEN, MERCHANT, &clock, ts::ctx(&mut scenario));
        clock::destroy_for_testing(clock);
        ts::return_shared(registry);
    };

    ts::next_tx(&mut scenario, PAYER);
    let registry = ts::take_shared<MerchantRegistry>(&mut scenario);
    let clock = new_clock_at(2000, ts::ctx(&mut scenario));
    let coin: Coin<SUI> = coin::mint_for_testing<SUI>(0, ts::ctx(&mut scenario));

    payments::pay<SUI>(
        &registry,
        TEST_UEN,
        coin,
        option::none(),
        0,
        option::none(),
        &clock,
        ts::ctx(&mut scenario),
    );

    clock::destroy_for_testing(clock);
    ts::return_shared(registry);
    ts::end(scenario);
}

// ─── Test: refund happy path ───────────────────────────────────────────

#[test]
fun refund_succeeds() {
    let mut scenario = ts::begin(ADMIN);
    setup_registry(&mut scenario);

    ts::next_tx(&mut scenario, MERCHANT);
    let clock = new_clock_at(1000, ts::ctx(&mut scenario));
    let refund_coin: Coin<SUI> = coin::mint_for_testing<SUI>(500_000, ts::ctx(&mut scenario));
    let receipt_id = vector[42u8, 42u8, 42u8, 42u8, 42u8, 42u8, 42u8, 42u8];

    payments::refund<SUI>(receipt_id, PAYER, refund_coin, &clock, ts::ctx(&mut scenario));

    clock::destroy_for_testing(clock);

    ts::next_tx(&mut scenario, PAYER);
    let received = ts::take_from_sender<Coin<SUI>>(&mut scenario);
    assert!(coin::value(&received) == 500_000, 0);
    ts::return_to_sender(&mut scenario, received);

    ts::end(scenario);
}

// ─── Test: refund zero fails ───────────────────────────────────────────

#[test]
#[expected_failure(abort_code = 12, location = suiqr::payments)] // E_REFUND_AMOUNT_ZERO
fun refund_zero_fails() {
    let mut scenario = ts::begin(ADMIN);
    setup_registry(&mut scenario);

    ts::next_tx(&mut scenario, MERCHANT);
    let clock = new_clock_at(1000, ts::ctx(&mut scenario));
    let refund_coin: Coin<SUI> = coin::mint_for_testing<SUI>(0, ts::ctx(&mut scenario));

    payments::refund<SUI>(vector[1u8, 2u8, 3u8], PAYER, refund_coin, &clock, ts::ctx(&mut scenario));

    clock::destroy_for_testing(clock);
    ts::end(scenario);
}

// ─── Test: update_merchant_address — owner only ────────────────────────

#[test]
fun update_merchant_address_by_owner_succeeds() {
    let mut scenario = ts::begin(ADMIN);
    setup_registry(&mut scenario);

    ts::next_tx(&mut scenario, ADMIN);
    {
        let mut registry = ts::take_shared<MerchantRegistry>(&mut scenario);
        let clock = new_clock_at(1000, ts::ctx(&mut scenario));
        payments::register_for_testing(&mut registry, TEST_UEN, MERCHANT, &clock, ts::ctx(&mut scenario));
        clock::destroy_for_testing(clock);
        ts::return_shared(registry);
    };

    ts::next_tx(&mut scenario, MERCHANT);
    let mut registry = ts::take_shared<MerchantRegistry>(&mut scenario);
    let clock = new_clock_at(2000, ts::ctx(&mut scenario));

    payments::update_merchant_address(&mut registry, TEST_UEN, OTHER_MERCHANT, &clock, ts::ctx(&mut scenario));
    assert!(payments::merchant_address(&registry, TEST_UEN) == OTHER_MERCHANT, 0);

    clock::destroy_for_testing(clock);
    ts::return_shared(registry);
    ts::end(scenario);
}

#[test]
#[expected_failure(abort_code = 3, location = suiqr::payments)] // E_NOT_MERCHANT_OWNER
fun update_merchant_address_by_non_owner_fails() {
    let mut scenario = ts::begin(ADMIN);
    setup_registry(&mut scenario);

    ts::next_tx(&mut scenario, ADMIN);
    {
        let mut registry = ts::take_shared<MerchantRegistry>(&mut scenario);
        let clock = new_clock_at(1000, ts::ctx(&mut scenario));
        payments::register_for_testing(&mut registry, TEST_UEN, MERCHANT, &clock, ts::ctx(&mut scenario));
        clock::destroy_for_testing(clock);
        ts::return_shared(registry);
    };

    ts::next_tx(&mut scenario, PAYER); // not the merchant
    let mut registry = ts::take_shared<MerchantRegistry>(&mut scenario);
    let clock = new_clock_at(2000, ts::ctx(&mut scenario));

    payments::update_merchant_address(&mut registry, TEST_UEN, OTHER_MERCHANT, &clock, ts::ctx(&mut scenario));

    clock::destroy_for_testing(clock);
    ts::return_shared(registry);
    ts::end(scenario);
}

// ─── Test: issuer pubkey rotation via AdminCap ─────────────────────────

#[test]
fun rotate_issuer_pubkey_succeeds() {
    let mut scenario = ts::begin(ADMIN);
    setup_registry(&mut scenario);
    init_issuer(&mut scenario, ISSUER_PUBKEY, TEST_CHAIN_ID);

    ts::next_tx(&mut scenario, ADMIN);
    let cap = ts::take_from_sender<AdminCap>(&mut scenario);
    let mut registry = ts::take_shared<MerchantRegistry>(&mut scenario);
    let clock = new_clock_at(5000, ts::ctx(&mut scenario));

    let new_key = vector[9u8, 9u8, 9u8, 9u8, 9u8, 9u8, 9u8, 9u8, 9u8, 9u8, 9u8, 9u8, 9u8, 9u8, 9u8, 9u8, 9u8, 9u8, 9u8, 9u8, 9u8, 9u8, 9u8, 9u8, 9u8, 9u8, 9u8, 9u8, 9u8, 9u8, 9u8, 9u8];
    payments::rotate_issuer_pubkey(&cap, &mut registry, new_key, &clock);
    assert!(payments::issuer_pubkey(&registry) == new_key, 0);

    clock::destroy_for_testing(clock);
    ts::return_to_sender(&mut scenario, cap);
    ts::return_shared(registry);
    ts::end(scenario);
}

// ─── Test: set_initial_issuer_pubkey twice fails ───────────────────────

#[test]
#[expected_failure(abort_code = 11, location = suiqr::payments)] // E_ISSUER_ALREADY_SET
fun set_initial_issuer_twice_fails() {
    let mut scenario = ts::begin(ADMIN);
    setup_registry(&mut scenario);
    init_issuer(&mut scenario, ISSUER_PUBKEY, TEST_CHAIN_ID);

    ts::next_tx(&mut scenario, ADMIN);
    let mut registry = ts::take_shared<MerchantRegistry>(&mut scenario);
    payments::set_initial_issuer_pubkey(&mut registry, ISSUER_PUBKEY, TEST_CHAIN_ID, ts::ctx(&mut scenario));
    ts::return_shared(registry);
    ts::end(scenario);
}

// ─── Test: only admin can set initial issuer ──────────────────────────

#[test]
#[expected_failure(abort_code = 7, location = suiqr::payments)] // E_NOT_ADMIN
fun set_initial_issuer_by_non_admin_fails() {
    let mut scenario = ts::begin(ADMIN);
    setup_registry(&mut scenario);

    ts::next_tx(&mut scenario, MERCHANT); // not admin
    let mut registry = ts::take_shared<MerchantRegistry>(&mut scenario);
    payments::set_initial_issuer_pubkey(&mut registry, ISSUER_PUBKEY, TEST_CHAIN_ID, ts::ctx(&mut scenario));
    ts::return_shared(registry);
    ts::end(scenario);
}

// ─── Test: uen_hash includes domain tag ────────────────────────────────

#[test]
fun uen_hash_differs_from_raw_hash() {
    // The registry key is blake2b256(b"PAYNOW_UEN_V1" || uen) and must differ
    // from blake2b256(uen) alone — otherwise the future PAYNOW_MOBILE_V1
    // namespace could collide with PAYNOW_UEN_V1.
    let raw_uen = TEST_UEN;
    let domain_keyed = payments::derive_uen_hash_for_testing(raw_uen);
    let raw_hash = sui::hash::blake2b256(&raw_uen);
    assert!(domain_keyed != raw_hash, 0);
    // vector<u8> has drop — no explicit destroy needed
}

// ─── Test: chain_id reads back ─────────────────────────────────────────

#[test]
fun chain_id_persists_across_calls() {
    let mut scenario = ts::begin(ADMIN);
    setup_registry(&mut scenario);
    init_issuer(&mut scenario, ISSUER_PUBKEY, 42);

    ts::next_tx(&mut scenario, ADMIN);
    let registry = ts::take_shared<MerchantRegistry>(&mut scenario);
    assert!(payments::chain_id(&registry) == 42, 0);
    ts::return_shared(registry);
    ts::end(scenario);
}
