#[test_only]
module quay::payments_tests;

use std::option;
use std::string;
use sui::clock::{Self, Clock};
use sui::coin::{Self, Coin};
use sui::sui::SUI;
use sui::test_scenario as ts;
use quay::payments::{Self, MerchantRegistry, AdminCap};

const ADMIN: address = @0xA1;
const MERCHANT: address = @0xA2; // matches test-vector claimer
const OTHER_MERCHANT: address = @0xA3;
const PAYER: address = @0xB1;

// ─── Test vectors ──────────────────────────────────────────────────────
// Generated by scripts/gen-test-vectors.ts — regenerate if ClaimMessage shape changes.
// issuer pubkey  hex: 2152f8d19b791d24453242e15f2eab6cb7cffa7b6a5ed30097960e069881db12
// signature       hex: 67eba883f3f69d4a183558329b1559773da6775b7f13880f6ebfa478f0891b4faf9edf89b9e2c6d553a0b596ec16464397f236c4444893a97bbe8d7eb75d960d

const ISSUER_PUBKEY: vector<u8> = vector[33u8, 82u8, 248u8, 209u8, 155u8, 121u8, 29u8, 36u8, 69u8, 50u8, 66u8, 225u8, 95u8, 46u8, 171u8, 108u8, 183u8, 207u8, 250u8, 123u8, 106u8, 94u8, 211u8, 0u8, 151u8, 150u8, 14u8, 6u8, 152u8, 129u8, 219u8, 18u8];
const TEST_SIGNATURE: vector<u8> = vector[103u8, 235u8, 168u8, 131u8, 243u8, 246u8, 157u8, 74u8, 24u8, 53u8, 88u8, 50u8, 155u8, 21u8, 89u8, 119u8, 61u8, 166u8, 119u8, 91u8, 127u8, 19u8, 136u8, 15u8, 110u8, 191u8, 164u8, 120u8, 240u8, 137u8, 27u8, 79u8, 175u8, 158u8, 223u8, 137u8, 185u8, 226u8, 198u8, 213u8, 83u8, 160u8, 181u8, 150u8, 236u8, 22u8, 70u8, 67u8, 151u8, 242u8, 54u8, 196u8, 68u8, 72u8, 147u8, 169u8, 123u8, 190u8, 141u8, 126u8, 183u8, 93u8, 150u8, 13u8];
const TEST_UEN: vector<u8> = vector[50u8, 48u8, 50u8, 48u8, 49u8, 50u8, 51u8, 52u8, 53u8, 90u8];
const TEST_NONCE: vector<u8> = vector[171u8, 171u8, 171u8, 171u8, 171u8, 171u8, 171u8, 171u8, 171u8, 171u8, 171u8, 171u8, 171u8, 171u8, 171u8, 171u8, 171u8, 171u8, 171u8, 171u8, 171u8, 171u8, 171u8, 171u8, 171u8, 171u8, 171u8, 171u8, 171u8, 171u8, 171u8, 171u8];
const TEST_EXPIRES_AT_MS: u64 = 9999999999999;
const TEST_CHAIN_ID: u8 = 0;
const TEST_EVIDENCE_HASH: vector<u8> = vector[238u8, 238u8, 238u8, 238u8, 238u8, 238u8, 238u8, 238u8, 238u8, 238u8, 238u8, 238u8, 238u8, 238u8, 238u8, 238u8, 238u8, 238u8, 238u8, 238u8, 238u8, 238u8, 238u8, 238u8, 238u8, 238u8, 238u8, 238u8, 238u8, 238u8, 238u8, 238u8];

// Pre-domain-rename signature (signed over the old SUIQR_CLAIM_V1 BCS message,
// which the V3 contract no longer accepts since the domain_tag was bumped to
// QUAY_CLAIM_V1). Used to prove the new contract rejects replays.
const OLD_SHAPE_SIGNATURE: vector<u8> = vector[32u8, 156u8, 166u8, 83u8, 44u8, 189u8, 1u8, 74u8, 79u8, 9u8, 136u8, 54u8, 164u8, 155u8, 84u8, 121u8, 115u8, 190u8, 198u8, 241u8, 251u8, 188u8, 65u8, 77u8, 122u8, 50u8, 224u8, 78u8, 74u8, 144u8, 219u8, 194u8, 195u8, 204u8, 86u8, 91u8, 147u8, 146u8, 174u8, 52u8, 162u8, 161u8, 94u8, 12u8, 176u8, 54u8, 54u8, 138u8, 93u8, 37u8, 246u8, 206u8, 15u8, 63u8, 148u8, 253u8, 199u8, 97u8, 22u8, 122u8, 97u8, 89u8, 121u8, 12u8];

// ─── Helpers ───────────────────────────────────────────────────────────

fun new_clock_at(t_ms: u64, ctx: &mut TxContext): Clock {
    let mut c = clock::create_for_testing(ctx);
    clock::set_for_testing(&mut c, t_ms);
    c
}

fun setup_registry(scenario: &mut ts::Scenario) {
    ts::next_tx(scenario, ADMIN);
    payments::init_for_testing(ts::ctx(scenario));
}

fun init_issuer(scenario: &mut ts::Scenario, pubkey: vector<u8>, chain_id: u8) {
    ts::next_tx(scenario, ADMIN);
    let mut registry = ts::take_shared<MerchantRegistry>(scenario);
    payments::set_initial_issuer_pubkey(&mut registry, pubkey, chain_id, ts::ctx(scenario));
    ts::return_shared(registry);
}

// ─── Test: happy-path register with real ed25519 vector ────────────────

#[test]
fun register_merchant_happy_path_real_signature() {
    let mut scenario = ts::begin(ADMIN);
    setup_registry(&mut scenario);
    init_issuer(&mut scenario, ISSUER_PUBKEY, TEST_CHAIN_ID);

    ts::next_tx(&mut scenario, MERCHANT);
    let mut registry = ts::take_shared<MerchantRegistry>(&mut scenario);
    let clock = new_clock_at(1000, ts::ctx(&mut scenario));

    payments::register_merchant(
        &mut registry,
        TEST_UEN,
        TEST_NONCE,
        TEST_SIGNATURE,
        TEST_EXPIRES_AT_MS,
        option::some(string::utf8(b"walrus-blob-id-deadbeef")),
        TEST_EVIDENCE_HASH,
        &clock,
        ts::ctx(&mut scenario),
    );

    assert!(payments::is_registered(&registry, TEST_UEN), 0);
    assert!(payments::merchant_address(&registry, TEST_UEN) == MERCHANT, 1);

    clock::destroy_for_testing(clock);
    ts::return_shared(registry);
    ts::end(scenario);
}

// ─── Test: init-race guard ─────────────────────────────────────────────

#[test]
#[expected_failure(abort_code = 8, location = quay::payments)] // E_REGISTRY_NOT_INITIALIZED
fun register_before_issuer_set_fails() {
    let mut scenario = ts::begin(ADMIN);
    setup_registry(&mut scenario);

    ts::next_tx(&mut scenario, MERCHANT);
    let mut registry = ts::take_shared<MerchantRegistry>(&mut scenario);
    let clock = new_clock_at(1000, ts::ctx(&mut scenario));

    payments::register_merchant(
        &mut registry,
        TEST_UEN,
        TEST_NONCE,
        TEST_SIGNATURE,
        TEST_EXPIRES_AT_MS,
        option::none(),
        TEST_EVIDENCE_HASH,
        &clock,
        ts::ctx(&mut scenario),
    );

    clock::destroy_for_testing(clock);
    ts::return_shared(registry);
    ts::end(scenario);
}

// ─── Test: expired attestation ─────────────────────────────────────────

#[test]
#[expected_failure(abort_code = 9, location = quay::payments)] // E_ATTESTATION_EXPIRED
fun register_expired_attestation_fails() {
    let mut scenario = ts::begin(ADMIN);
    setup_registry(&mut scenario);
    init_issuer(&mut scenario, ISSUER_PUBKEY, TEST_CHAIN_ID);

    ts::next_tx(&mut scenario, MERCHANT);
    let mut registry = ts::take_shared<MerchantRegistry>(&mut scenario);
    let expires_at_ms = 1000u64;
    let clock = new_clock_at(2000, ts::ctx(&mut scenario)); // past expiry

    payments::register_merchant(
        &mut registry,
        TEST_UEN,
        TEST_NONCE,
        TEST_SIGNATURE,
        expires_at_ms,
        option::none(),
        TEST_EVIDENCE_HASH,
        &clock,
        ts::ctx(&mut scenario),
    );

    clock::destroy_for_testing(clock);
    ts::return_shared(registry);
    ts::end(scenario);
}

// ─── Test: bad signature ───────────────────────────────────────────────

#[test]
#[expected_failure(abort_code = 5, location = quay::payments)] // E_INVALID_ATTESTATION
fun register_bad_signature_fails() {
    let mut scenario = ts::begin(ADMIN);
    setup_registry(&mut scenario);
    init_issuer(&mut scenario, ISSUER_PUBKEY, TEST_CHAIN_ID);

    ts::next_tx(&mut scenario, MERCHANT);
    let mut registry = ts::take_shared<MerchantRegistry>(&mut scenario);
    let clock = new_clock_at(1000, ts::ctx(&mut scenario));

    // Use a zeroed signature — guaranteed invalid
    let bad_sig = vector[0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8];

    payments::register_merchant(
        &mut registry,
        TEST_UEN,
        TEST_NONCE,
        bad_sig,
        TEST_EXPIRES_AT_MS,
        option::none(),
        TEST_EVIDENCE_HASH,
        &clock,
        ts::ctx(&mut scenario),
    );

    clock::destroy_for_testing(clock);
    ts::return_shared(registry);
    ts::end(scenario);
}

// ─── Test: wrong chain_id rejects the signature ────────────────────────

#[test]
#[expected_failure(abort_code = 5, location = quay::payments)] // E_INVALID_ATTESTATION (BCS msg differs)
fun register_wrong_chain_id_fails() {
    let mut scenario = ts::begin(ADMIN);
    setup_registry(&mut scenario);
    // Init with chain_id=1; vector was signed for chain_id=0
    init_issuer(&mut scenario, ISSUER_PUBKEY, 1);

    ts::next_tx(&mut scenario, MERCHANT);
    let mut registry = ts::take_shared<MerchantRegistry>(&mut scenario);
    let clock = new_clock_at(1000, ts::ctx(&mut scenario));

    payments::register_merchant(
        &mut registry,
        TEST_UEN,
        TEST_NONCE,
        TEST_SIGNATURE,
        TEST_EXPIRES_AT_MS,
        option::none(),
        TEST_EVIDENCE_HASH,
        &clock,
        ts::ctx(&mut scenario),
    );

    clock::destroy_for_testing(clock);
    ts::return_shared(registry);
    ts::end(scenario);
}

// ─── Test: double-claim same UEN fails ─────────────────────────────────

#[test]
#[expected_failure(abort_code = 1, location = quay::payments)] // E_UEN_ALREADY_CLAIMED
fun double_claim_uen_fails() {
    let mut scenario = ts::begin(ADMIN);
    setup_registry(&mut scenario);
    init_issuer(&mut scenario, ISSUER_PUBKEY, TEST_CHAIN_ID);

    // First claim — real vector, succeeds
    ts::next_tx(&mut scenario, MERCHANT);
    {
        let mut registry = ts::take_shared<MerchantRegistry>(&mut scenario);
        let clock = new_clock_at(1000, ts::ctx(&mut scenario));
        payments::register_merchant(
            &mut registry,
            TEST_UEN,
            TEST_NONCE,
            TEST_SIGNATURE,
            TEST_EXPIRES_AT_MS,
            option::none(),
            TEST_EVIDENCE_HASH,
            &clock,
            ts::ctx(&mut scenario),
        );
        clock::destroy_for_testing(clock);
        ts::return_shared(registry);
    };

    // Second claim of same UEN — should abort with E_UEN_ALREADY_CLAIMED
    // Use a different nonce so we hit the UEN_ALREADY check, not nonce-replay.
    ts::next_tx(&mut scenario, MERCHANT);
    let mut registry = ts::take_shared<MerchantRegistry>(&mut scenario);
    let clock = new_clock_at(2000, ts::ctx(&mut scenario));
    let other_nonce = vector[1u8, 2u8, 3u8, 4u8, 5u8, 6u8, 7u8, 8u8, 9u8, 10u8, 11u8, 12u8, 13u8, 14u8, 15u8, 16u8, 17u8, 18u8, 19u8, 20u8, 21u8, 22u8, 23u8, 24u8, 25u8, 26u8, 27u8, 28u8, 29u8, 30u8, 31u8, 32u8];

    payments::register_merchant(
        &mut registry,
        TEST_UEN,
        other_nonce,
        TEST_SIGNATURE, // sig won't verify but UEN check fires first
        TEST_EXPIRES_AT_MS,
        option::none(),
        TEST_EVIDENCE_HASH,
        &clock,
        ts::ctx(&mut scenario),
    );

    clock::destroy_for_testing(clock);
    ts::return_shared(registry);
    ts::end(scenario);
}

// ─── Test: pay happy path ──────────────────────────────────────────────

#[test]
fun pay_succeeds_and_emits_receipt() {
    let mut scenario = ts::begin(ADMIN);
    setup_registry(&mut scenario);

    // Use test bypass to register (we exercise register path in other tests)
    ts::next_tx(&mut scenario, ADMIN);
    {
        let mut registry = ts::take_shared<MerchantRegistry>(&mut scenario);
        let clock = new_clock_at(1000, ts::ctx(&mut scenario));
        payments::register_for_testing(
            &mut registry,
            TEST_UEN,
            MERCHANT,
            &clock,
            ts::ctx(&mut scenario),
        );
        clock::destroy_for_testing(clock);
        ts::return_shared(registry);
    };

    // Payer pays 1_000_000 mist (= 0.001 SUI) — small ticket
    ts::next_tx(&mut scenario, PAYER);
    let registry = ts::take_shared<MerchantRegistry>(&mut scenario);
    let clock = new_clock_at(2000, ts::ctx(&mut scenario));
    let coin: Coin<SUI> = coin::mint_for_testing<SUI>(1_000_000, ts::ctx(&mut scenario));

    payments::pay<SUI>(
        &registry,
        TEST_UEN,
        coin,
        option::some(b"chicken rice"),
        150, // SGD $1.50 minor units
        option::some(b"quote-meta-bcs-bytes"),
        &clock,
        ts::ctx(&mut scenario),
    );

    clock::destroy_for_testing(clock);
    ts::return_shared(registry);

    // Verify merchant received the coin
    ts::next_tx(&mut scenario, MERCHANT);
    let received = ts::take_from_sender<Coin<SUI>>(&mut scenario);
    assert!(coin::value(&received) == 1_000_000, 0);
    ts::return_to_sender(&mut scenario, received);

    ts::end(scenario);
}

// ─── Test: pay to unregistered UEN fails ───────────────────────────────

#[test]
#[expected_failure(abort_code = 2, location = quay::payments)] // E_UEN_NOT_REGISTERED
fun pay_unregistered_uen_fails() {
    let mut scenario = ts::begin(ADMIN);
    setup_registry(&mut scenario);

    ts::next_tx(&mut scenario, PAYER);
    let registry = ts::take_shared<MerchantRegistry>(&mut scenario);
    let clock = new_clock_at(1000, ts::ctx(&mut scenario));
    let coin: Coin<SUI> = coin::mint_for_testing<SUI>(1_000_000, ts::ctx(&mut scenario));

    payments::pay<SUI>(
        &registry,
        TEST_UEN, // never registered
        coin,
        option::none(),
        0,
        option::none(),
        &clock,
        ts::ctx(&mut scenario),
    );

    clock::destroy_for_testing(clock);
    ts::return_shared(registry);
    ts::end(scenario);
}

// ─── Test: pay zero amount fails ───────────────────────────────────────

#[test]
#[expected_failure(abort_code = 4, location = quay::payments)] // E_PAYMENT_BELOW_MIN
fun pay_zero_amount_fails() {
    let mut scenario = ts::begin(ADMIN);
    setup_registry(&mut scenario);

    ts::next_tx(&mut scenario, ADMIN);
    {
        let mut registry = ts::take_shared<MerchantRegistry>(&mut scenario);
        let clock = new_clock_at(1000, ts::ctx(&mut scenario));
        payments::register_for_testing(&mut registry, TEST_UEN, MERCHANT, &clock, ts::ctx(&mut scenario));
        clock::destroy_for_testing(clock);
        ts::return_shared(registry);
    };

    ts::next_tx(&mut scenario, PAYER);
    let registry = ts::take_shared<MerchantRegistry>(&mut scenario);
    let clock = new_clock_at(2000, ts::ctx(&mut scenario));
    let coin: Coin<SUI> = coin::mint_for_testing<SUI>(0, ts::ctx(&mut scenario));

    payments::pay<SUI>(
        &registry,
        TEST_UEN,
        coin,
        option::none(),
        0,
        option::none(),
        &clock,
        ts::ctx(&mut scenario),
    );

    clock::destroy_for_testing(clock);
    ts::return_shared(registry);
    ts::end(scenario);
}

// ─── Test: refund happy path ───────────────────────────────────────────

#[test]
fun refund_succeeds() {
    let mut scenario = ts::begin(ADMIN);
    setup_registry(&mut scenario);

    ts::next_tx(&mut scenario, MERCHANT);
    let clock = new_clock_at(1000, ts::ctx(&mut scenario));
    let refund_coin: Coin<SUI> = coin::mint_for_testing<SUI>(500_000, ts::ctx(&mut scenario));
    let receipt_id = vector[42u8, 42u8, 42u8, 42u8, 42u8, 42u8, 42u8, 42u8];

    payments::refund<SUI>(receipt_id, PAYER, refund_coin, &clock, ts::ctx(&mut scenario));

    clock::destroy_for_testing(clock);

    ts::next_tx(&mut scenario, PAYER);
    let received = ts::take_from_sender<Coin<SUI>>(&mut scenario);
    assert!(coin::value(&received) == 500_000, 0);
    ts::return_to_sender(&mut scenario, received);

    ts::end(scenario);
}

// ─── Test: refund zero fails ───────────────────────────────────────────

#[test]
#[expected_failure(abort_code = 12, location = quay::payments)] // E_REFUND_AMOUNT_ZERO
fun refund_zero_fails() {
    let mut scenario = ts::begin(ADMIN);
    setup_registry(&mut scenario);

    ts::next_tx(&mut scenario, MERCHANT);
    let clock = new_clock_at(1000, ts::ctx(&mut scenario));
    let refund_coin: Coin<SUI> = coin::mint_for_testing<SUI>(0, ts::ctx(&mut scenario));

    payments::refund<SUI>(vector[1u8, 2u8, 3u8], PAYER, refund_coin, &clock, ts::ctx(&mut scenario));

    clock::destroy_for_testing(clock);
    ts::end(scenario);
}

// ─── Test: update_merchant_address — owner only ────────────────────────

#[test]
fun update_merchant_address_by_owner_succeeds() {
    let mut scenario = ts::begin(ADMIN);
    setup_registry(&mut scenario);

    ts::next_tx(&mut scenario, ADMIN);
    {
        let mut registry = ts::take_shared<MerchantRegistry>(&mut scenario);
        let clock = new_clock_at(1000, ts::ctx(&mut scenario));
        payments::register_for_testing(&mut registry, TEST_UEN, MERCHANT, &clock, ts::ctx(&mut scenario));
        clock::destroy_for_testing(clock);
        ts::return_shared(registry);
    };

    ts::next_tx(&mut scenario, MERCHANT);
    let mut registry = ts::take_shared<MerchantRegistry>(&mut scenario);
    let clock = new_clock_at(2000, ts::ctx(&mut scenario));

    payments::update_merchant_address(&mut registry, TEST_UEN, OTHER_MERCHANT, &clock, ts::ctx(&mut scenario));
    assert!(payments::merchant_address(&registry, TEST_UEN) == OTHER_MERCHANT, 0);

    clock::destroy_for_testing(clock);
    ts::return_shared(registry);
    ts::end(scenario);
}

#[test]
#[expected_failure(abort_code = 3, location = quay::payments)] // E_NOT_MERCHANT_OWNER
fun update_merchant_address_by_non_owner_fails() {
    let mut scenario = ts::begin(ADMIN);
    setup_registry(&mut scenario);

    ts::next_tx(&mut scenario, ADMIN);
    {
        let mut registry = ts::take_shared<MerchantRegistry>(&mut scenario);
        let clock = new_clock_at(1000, ts::ctx(&mut scenario));
        payments::register_for_testing(&mut registry, TEST_UEN, MERCHANT, &clock, ts::ctx(&mut scenario));
        clock::destroy_for_testing(clock);
        ts::return_shared(registry);
    };

    ts::next_tx(&mut scenario, PAYER); // not the merchant
    let mut registry = ts::take_shared<MerchantRegistry>(&mut scenario);
    let clock = new_clock_at(2000, ts::ctx(&mut scenario));

    payments::update_merchant_address(&mut registry, TEST_UEN, OTHER_MERCHANT, &clock, ts::ctx(&mut scenario));

    clock::destroy_for_testing(clock);
    ts::return_shared(registry);
    ts::end(scenario);
}

// ─── Test: issuer pubkey rotation via AdminCap ─────────────────────────

#[test]
fun rotate_issuer_pubkey_succeeds() {
    let mut scenario = ts::begin(ADMIN);
    setup_registry(&mut scenario);
    init_issuer(&mut scenario, ISSUER_PUBKEY, TEST_CHAIN_ID);

    ts::next_tx(&mut scenario, ADMIN);
    let cap = ts::take_from_sender<AdminCap>(&mut scenario);
    let mut registry = ts::take_shared<MerchantRegistry>(&mut scenario);
    let clock = new_clock_at(5000, ts::ctx(&mut scenario));

    let new_key = vector[9u8, 9u8, 9u8, 9u8, 9u8, 9u8, 9u8, 9u8, 9u8, 9u8, 9u8, 9u8, 9u8, 9u8, 9u8, 9u8, 9u8, 9u8, 9u8, 9u8, 9u8, 9u8, 9u8, 9u8, 9u8, 9u8, 9u8, 9u8, 9u8, 9u8, 9u8, 9u8];
    payments::rotate_issuer_pubkey(&cap, &mut registry, new_key, &clock);
    assert!(payments::issuer_pubkey(&registry) == new_key, 0);

    clock::destroy_for_testing(clock);
    ts::return_to_sender(&mut scenario, cap);
    ts::return_shared(registry);
    ts::end(scenario);
}

// ─── Test: set_initial_issuer_pubkey twice fails ───────────────────────

#[test]
#[expected_failure(abort_code = 11, location = quay::payments)] // E_ISSUER_ALREADY_SET
fun set_initial_issuer_twice_fails() {
    let mut scenario = ts::begin(ADMIN);
    setup_registry(&mut scenario);
    init_issuer(&mut scenario, ISSUER_PUBKEY, TEST_CHAIN_ID);

    ts::next_tx(&mut scenario, ADMIN);
    let mut registry = ts::take_shared<MerchantRegistry>(&mut scenario);
    payments::set_initial_issuer_pubkey(&mut registry, ISSUER_PUBKEY, TEST_CHAIN_ID, ts::ctx(&mut scenario));
    ts::return_shared(registry);
    ts::end(scenario);
}

// ─── Test: only admin can set initial issuer ──────────────────────────

#[test]
#[expected_failure(abort_code = 7, location = quay::payments)] // E_NOT_ADMIN
fun set_initial_issuer_by_non_admin_fails() {
    let mut scenario = ts::begin(ADMIN);
    setup_registry(&mut scenario);

    ts::next_tx(&mut scenario, MERCHANT); // not admin
    let mut registry = ts::take_shared<MerchantRegistry>(&mut scenario);
    payments::set_initial_issuer_pubkey(&mut registry, ISSUER_PUBKEY, TEST_CHAIN_ID, ts::ctx(&mut scenario));
    ts::return_shared(registry);
    ts::end(scenario);
}

// ─── Test: uen_hash includes domain tag ────────────────────────────────

#[test]
fun uen_hash_differs_from_raw_hash() {
    // The registry key is blake2b256(b"PAYNOW_UEN_V1" || uen) and must differ
    // from blake2b256(uen) alone — otherwise the future PAYNOW_MOBILE_V1
    // namespace could collide with PAYNOW_UEN_V1.
    let raw_uen = TEST_UEN;
    let domain_keyed = payments::derive_uen_hash_for_testing(raw_uen);
    let raw_hash = sui::hash::blake2b256(&raw_uen);
    assert!(domain_keyed != raw_hash, 0);
    // vector<u8> has drop — no explicit destroy needed
}

// ─── Test: chain_id reads back ─────────────────────────────────────────

#[test]
fun chain_id_persists_across_calls() {
    let mut scenario = ts::begin(ADMIN);
    setup_registry(&mut scenario);
    init_issuer(&mut scenario, ISSUER_PUBKEY, 42);

    ts::next_tx(&mut scenario, ADMIN);
    let registry = ts::take_shared<MerchantRegistry>(&mut scenario);
    assert!(payments::chain_id(&registry) == 42, 0);
    ts::return_shared(registry);
    ts::end(scenario);
}

// ─── REGRESSION (D9 #1): old-shape attestation rejected by new contract ─

/// CRITICAL — proves the new contract refuses to verify a signature made
/// against the OLD ClaimMessage shape (without evidence_hash). Without this
/// check, an attacker who held a pre-migration attestation could register
/// under the new contract without producing any evidence. The BCS shape
/// change is itself a security boundary.
#[test]
#[expected_failure(abort_code = 5, location = quay::payments)] // E_INVALID_ATTESTATION
fun register_old_shape_attestation_rejected() {
    let mut scenario = ts::begin(ADMIN);
    setup_registry(&mut scenario);
    init_issuer(&mut scenario, ISSUER_PUBKEY, TEST_CHAIN_ID);

    ts::next_tx(&mut scenario, MERCHANT);
    let mut registry = ts::take_shared<MerchantRegistry>(&mut scenario);
    let clock = new_clock_at(1000, ts::ctx(&mut scenario));

    payments::register_merchant(
        &mut registry,
        TEST_UEN,
        TEST_NONCE,
        OLD_SHAPE_SIGNATURE, // signature over BCS(ClaimMessage_v1, no evidence_hash)
        TEST_EXPIRES_AT_MS,
        option::none(),
        TEST_EVIDENCE_HASH,
        &clock,
        ts::ctx(&mut scenario),
    );

    clock::destroy_for_testing(clock);
    ts::return_shared(registry);
    ts::end(scenario);
}

// ─── REGRESSION (D9 #2): pay works on new MerchantEntry shape ──────────

/// CRITICAL — register via the real-signature path (exercising the new
/// uen_raw + evidence_hash fields on MerchantEntry) and then pay against
/// it. Verifies the new entry shape doesn't break the pay flow.
#[test]
fun pay_works_after_real_register_with_evidence() {
    let mut scenario = ts::begin(ADMIN);
    setup_registry(&mut scenario);
    init_issuer(&mut scenario, ISSUER_PUBKEY, TEST_CHAIN_ID);

    // Real register with evidence_hash
    ts::next_tx(&mut scenario, MERCHANT);
    {
        let mut registry = ts::take_shared<MerchantRegistry>(&mut scenario);
        let clock = new_clock_at(1000, ts::ctx(&mut scenario));
        payments::register_merchant(
            &mut registry,
            TEST_UEN,
            TEST_NONCE,
            TEST_SIGNATURE,
            TEST_EXPIRES_AT_MS,
            option::some(string::utf8(b"walrus-blob-xyz")),
            TEST_EVIDENCE_HASH,
            &clock,
            ts::ctx(&mut scenario),
        );
        clock::destroy_for_testing(clock);
        ts::return_shared(registry);
    };

    // Pay against the freshly-shaped entry
    ts::next_tx(&mut scenario, PAYER);
    let registry = ts::take_shared<MerchantRegistry>(&mut scenario);
    let clock = new_clock_at(2000, ts::ctx(&mut scenario));
    let coin: Coin<SUI> = coin::mint_for_testing<SUI>(500_000, ts::ctx(&mut scenario));

    payments::pay<SUI>(
        &registry,
        TEST_UEN,
        coin,
        option::some(b"latte"),
        450, // S$4.50
        option::some(b"v2-quote-metadata-bcs"),
        &clock,
        ts::ctx(&mut scenario),
    );

    clock::destroy_for_testing(clock);
    ts::return_shared(registry);

    // Merchant received it
    ts::next_tx(&mut scenario, MERCHANT);
    let received = ts::take_from_sender<Coin<SUI>>(&mut scenario);
    assert!(coin::value(&received) == 500_000, 0);
    ts::return_to_sender(&mut scenario, received);

    ts::end(scenario);
}

// ─── REGRESSION (D9 #3): evidence_hash mismatch fails signature check ──

/// CRITICAL — the issuer signs over a specific evidence_hash. If a merchant
/// submits a register tx with a DIFFERENT evidence_hash than the one signed,
/// the BCS message differs and ed25519 verification fails. This is what makes
/// evidence binding non-theatrical: you can't swap evidence post-signing.
#[test]
#[expected_failure(abort_code = 5, location = quay::payments)] // E_INVALID_ATTESTATION
fun register_with_wrong_evidence_hash_fails() {
    let mut scenario = ts::begin(ADMIN);
    setup_registry(&mut scenario);
    init_issuer(&mut scenario, ISSUER_PUBKEY, TEST_CHAIN_ID);

    ts::next_tx(&mut scenario, MERCHANT);
    let mut registry = ts::take_shared<MerchantRegistry>(&mut scenario);
    let clock = new_clock_at(1000, ts::ctx(&mut scenario));

    // 32 zero bytes — definitely not what the issuer signed over.
    let wrong_evidence = vector[0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8];

    payments::register_merchant(
        &mut registry,
        TEST_UEN,
        TEST_NONCE,
        TEST_SIGNATURE, // valid sig but over TEST_EVIDENCE_HASH (not zeros)
        TEST_EXPIRES_AT_MS,
        option::none(),
        wrong_evidence,
        &clock,
        ts::ctx(&mut scenario),
    );

    clock::destroy_for_testing(clock);
    ts::return_shared(registry);
    ts::end(scenario);
}
