/**
 * Generate hardcoded test vectors for payments_tests.move.
 * Run: bun run scripts/gen-test-vectors.ts
 * Pastes the output into the Move test file as constants.
 */
import { Ed25519Keypair } from "@mysten/sui/keypairs/ed25519";
import { bcs } from "@mysten/sui/bcs";

// Stable test seed so vectors are reproducible (not for production).
const SEED = new Uint8Array(32).fill(0x42);
const issuerKp = Ed25519Keypair.fromSecretKey(SEED);
const issuerPub = issuerKp.getPublicKey().toRawBytes();

const ClaimMessage = bcs.struct("ClaimMessage", {
  domain_tag: bcs.vector(bcs.u8()),
  chain_id: bcs.u8(),
  uen: bcs.vector(bcs.u8()),
  claimer: bcs.bytes(32),
  nonce: bcs.vector(bcs.u8()),
  expires_at_ms: bcs.u64(),
  evidence_hash: bcs.vector(bcs.u8()),
});

function hex(b: Uint8Array): string {
  return Array.from(b).map((x) => x.toString(16).padStart(2, "0")).join("");
}
function vecLit(b: Uint8Array): string {
  return `vector[${Array.from(b).map((x) => `${x}u8`).join(", ")}]`;
}

const CHAIN_ID_TEST = 0;
const CLAIMER_ADDR = new Uint8Array(32);
CLAIMER_ADDR[31] = 0xA2; // matches @0xA2 in Move tests
const UEN = new TextEncoder().encode("202012345Z"); // sample SG UEN
const NONCE = new Uint8Array(32).fill(0xAB);
const EXPIRES_AT_MS = 9_999_999_999_999n; // far future
// blake2b256("test-evidence") — stable bytes for reproducible vectors.
const EVIDENCE_HASH = new Uint8Array(32).fill(0xEE);

const msgBytes = ClaimMessage.serialize({
  domain_tag: Array.from(new TextEncoder().encode("QUAY_CLAIM_V1")),
  chain_id: CHAIN_ID_TEST,
  uen: Array.from(UEN),
  claimer: CLAIMER_ADDR,
  nonce: Array.from(NONCE),
  expires_at_ms: EXPIRES_AT_MS,
  evidence_hash: Array.from(EVIDENCE_HASH),
}).toBytes();

// blake2b256
const { blake2b } = await import("@noble/hashes/blake2.js");
const msgHash = blake2b(msgBytes, { dkLen: 32 });
const sig = await issuerKp.sign(msgHash);

console.log("// Generated by scripts/gen-test-vectors.ts — regenerate if struct changes");
console.log("//");
console.log(`// issuer pubkey  hex: ${hex(issuerPub)}`);
console.log(`// signature       hex: ${hex(sig)}`);
console.log(`// claim msg hash  hex: ${hex(msgHash)}`);
console.log("");
console.log(`const ISSUER_PUBKEY: vector<u8> = ${vecLit(issuerPub)};`);
console.log(`const TEST_SIGNATURE: vector<u8> = ${vecLit(sig)};`);
console.log(`const TEST_UEN: vector<u8> = ${vecLit(UEN)};`);
console.log(`const TEST_NONCE: vector<u8> = ${vecLit(NONCE)};`);
console.log(`const TEST_EXPIRES_AT_MS: u64 = ${EXPIRES_AT_MS};`);
console.log(`const TEST_CLAIMER: address = @0xA2;`);
console.log(`const TEST_CHAIN_ID: u8 = ${CHAIN_ID_TEST};`);
console.log(`const TEST_EVIDENCE_HASH: vector<u8> = ${vecLit(EVIDENCE_HASH)};`);
